export interface SymptomContent {
  metaTitle: string;
  metaDescription: string;
  keywords: string;
  intro: string;
  causes: { name: string; description: string }[];
  redFlags: string[];
  whenToAct: string;
}

export interface Symptom {
  slug: string;
  zone: string;
  emoji: string;
  related: string[];
  content: {
    es: SymptomContent;
    en: SymptomContent;
    zh: SymptomContent;
    ru: SymptomContent;
  };
}

export const SYMPTOMS: Symptom[] = [
  {
    slug: 'dolor-de-cabeza',
    zone: 'cabeza',
    emoji: '🧠',
    related: ['mareos-y-vertigo', 'dolor-de-cuello', 'dolor-de-garganta'],
    content: {
      es: {
        metaTitle: 'Dolor de cabeza: causas, tipos y cuándo ir al médico',
        metaDescription: 'Información general sobre el dolor de cabeza: causas frecuentes, tipos de cefalea, señales de alarma y cuándo consultar con un médico.',
        keywords: 'dolor de cabeza, cefalea, migraña, jaqueca, dolor de cabeza causas',
        intro: 'El dolor de cabeza o cefalea es uno de los síntomas más frecuentes en la población general. Puede aparecer por múltiples motivos y la gran mayoría de los casos son benignos y autolimitados.',
        causes: [
          { name: 'Tensión muscular', description: 'La causa más frecuente. Aparece por estrés, mala postura o fatiga. El dolor es opresivo y bilateral.' },
          { name: 'Migraña', description: 'Dolor intenso y pulsátil, generalmente unilateral, que puede acompañarse de náuseas y sensibilidad a la luz.' },
          { name: 'Deshidratación', description: 'La falta de líquidos genera un dolor difuso que mejora rápidamente al hidratarse.' },
          { name: 'Sinusitis', description: 'Inflamación de los senos paranasales que produce presión y dolor frontal o alrededor de los ojos.' },
          { name: 'Tensión ocular', description: 'Pasar muchas horas frente a pantallas genera fatiga visual y dolor de cabeza frontal.' },
        ],
        redFlags: [
          'Dolor de inicio brusco e intensísimo ("el peor de tu vida")',
          'Fiebre alta acompañando el dolor',
          'Rigidez de cuello',
          'Confusión, dificultad para hablar o pérdida de conciencia',
          'Visión doble o pérdida de visión',
          'Dolor que empeora progresivamente en días',
        ],
        whenToAct: 'Si el dolor es leve y cede con descanso e hidratación, observa durante unas horas. Si es recurrente, consulta con tu médico. Si aparece alguna señal de alarma, busca atención médica urgente o llama al 112.',
      },
      en: {
        metaTitle: 'Headache: causes, types and when to see a doctor',
        metaDescription: 'General information about headaches: common causes, types of headache, warning signs and when to consult a doctor.',
        keywords: 'headache, migraine, cephalalgia, tension headache, headache causes',
        intro: 'Headache is one of the most common symptoms in the general population. It can appear for multiple reasons and the vast majority of cases are benign and self-limiting.',
        causes: [
          { name: 'Muscle tension', description: 'The most frequent cause. Appears due to stress, poor posture or fatigue. Pain is pressing and bilateral.' },
          { name: 'Migraine', description: 'Intense, pulsating pain, usually one-sided, which may be accompanied by nausea and light sensitivity.' },
          { name: 'Dehydration', description: 'Lack of fluids creates diffuse pain that quickly improves with hydration.' },
          { name: 'Sinusitis', description: 'Inflammation of the sinuses that produces pressure and frontal pain or around the eyes.' },
          { name: 'Eye strain', description: 'Spending many hours in front of screens creates visual fatigue and frontal headache.' },
        ],
        redFlags: [
          'Sudden, extremely intense pain ("worst of your life")',
          'High fever accompanying the pain',
          'Neck stiffness',
          'Confusion, difficulty speaking or loss of consciousness',
          'Double vision or vision loss',
          'Pain that progressively worsens over days',
        ],
        whenToAct: 'If the pain is mild and subsides with rest and hydration, observe for a few hours. If recurrent, consult your doctor. If any warning sign appears, seek urgent medical attention or call emergency services.',
      },
      zh: {
        metaTitle: '头痛：原因、类型及何时就医',
        metaDescription: '关于头痛的一般信息：常见原因、头痛类型、警告信号以及何时咨询医生。',
        keywords: '头痛, 偏头痛, 紧张性头痛, 头痛原因',
        intro: '头痛是一般人群中最常见的症状之一。它可能由多种原因引起，绝大多数情况是良性和自限性的。',
        causes: [
          { name: '肌肉紧张', description: '最常见的原因。由压力、不良姿势或疲劳引起。疼痛为压迫性和双侧性。' },
          { name: '偏头痛', description: '通常为单侧的强烈搏动性疼痛，可能伴有恶心和对光敏感。' },
          { name: '脱水', description: '缺乏液体会产生弥漫性疼痛，补水后迅速改善。' },
          { name: '鼻窦炎', description: '鼻窦炎症引起压力和额部疼痛或眼周疼痛。' },
          { name: '视疲劳', description: '长时间面对屏幕会产生视觉疲劳和额部头痛。' },
        ],
        redFlags: [
          '突然发作的极度剧烈疼痛（"有生以来最严重的"）',
          '伴随高烧的疼痛',
          '颈部僵硬',
          '意识混乱、言语困难或意识丧失',
          '复视或视力丧失',
          '疼痛在数天内逐渐加重',
        ],
        whenToAct: '如果疼痛轻微，休息和补水后缓解，观察几个小时。如果反复发作，咨询医生。如果出现任何警告信号，立即寻求紧急医疗救助或拨打急救电话。',
      },
      ru: {
        metaTitle: 'Головная боль: причины, виды и когда обращаться к врачу',
        metaDescription: 'Общая информация о головной боли: частые причины, виды головной боли, тревожные признаки и когда обратиться к врачу.',
        keywords: 'головная боль, мигрень, цефалгия, головная боль причины',
        intro: 'Головная боль — один из самых частых симптомов в общей популяции. Она может появляться по разным причинам, и в подавляющем большинстве случаев носит доброкачественный и самоограничивающийся характер.',
        causes: [
          { name: 'Мышечное напряжение', description: 'Наиболее частая причина. Появляется из-за стресса, плохой осанки или усталости. Боль давящая и двусторонняя.' },
          { name: 'Мигрень', description: 'Интенсивная пульсирующая боль, обычно односторонняя, которая может сопровождаться тошнотой и светочувствительностью.' },
          { name: 'Обезвоживание', description: 'Недостаток жидкости вызывает диффузную боль, которая быстро проходит при употреблении жидкости.' },
          { name: 'Синусит', description: 'Воспаление придаточных пазух носа, вызывающее давление и боль в лобной области или вокруг глаз.' },
          { name: 'Усталость глаз', description: 'Длительная работа за экранами вызывает зрительную усталость и боль в лобной части головы.' },
        ],
        redFlags: [
          'Внезапная крайне интенсивная боль ("худшая в жизни")',
          'Высокая температура с болью',
          'Ригидность затылка',
          'Спутанность сознания, трудности с речью или потеря сознания',
          'Двоение в глазах или потеря зрения',
          'Боль, которая прогрессивно усиливается в течение нескольких дней',
        ],
        whenToAct: 'Если боль слабая и проходит после отдыха и употребления жидкости, наблюдайте несколько часов. При повторяющихся случаях проконсультируйтесь с врачом. При появлении тревожных признаков немедленно обратитесь за медицинской помощью.',
      },
    },
  },
  {
    slug: 'dolor-de-espalda',
    zone: 'espalda_alta',
    emoji: '🔙',
    related: ['dolor-lumbar', 'dolor-de-cuello', 'dolor-muscular'],
    content: {
      es: {
        metaTitle: 'Dolor de espalda: causas y cuándo preocuparse',
        metaDescription: 'Guía informativa sobre el dolor de espalda: causas más frecuentes, factores de riesgo, señales de alarma y cuándo consultar al médico.',
        keywords: 'dolor de espalda, dorsalgia, dolor espalda alta, dolor espalda causas',
        intro: 'El dolor de espalda afecta a millones de personas y es una de las principales causas de baja laboral. En la mayoría de los casos tiene origen muscular o postural y mejora con el tiempo.',
        causes: [
          { name: 'Contractura muscular', description: 'Tensión excesiva en los músculos de la espalda por malas posturas, esfuerzos o sedentarismo.' },
          { name: 'Hernia discal', description: 'El disco intervertebral presiona un nervio, causando dolor que puede irradiar al brazo o pierna.' },
          { name: 'Escoliosis', description: 'Curvatura lateral de la columna que genera desequilibrio muscular y dolor crónico.' },
          { name: 'Osteoporosis', description: 'Pérdida de densidad ósea que hace las vértebras más frágiles y propensas a fracturas.' },
          { name: 'Estrés y ansiedad', description: 'La tensión emocional se manifiesta frecuentemente como contracturas en la zona dorsal.' },
        ],
        redFlags: [
          'Dolor que aparece tras un traumatismo o caída',
          'Pérdida de fuerza o sensibilidad en brazos o piernas',
          'Fiebre acompañando el dolor de espalda',
          'Dolor nocturno que no mejora con ninguna postura',
          'Pérdida de control de vejiga o intestino',
        ],
        whenToAct: 'Para el dolor de espalda mecánico común mantén actividad moderada y aplica calor local. Si no mejora en 2 semanas o aparece alguna señal de alarma, consulta con tu médico.',
      },
      en: {
        metaTitle: 'Back pain: causes and when to worry',
        metaDescription: 'Informational guide on back pain: most common causes, risk factors, warning signs and when to consult a doctor.',
        keywords: 'back pain, dorsalgia, upper back pain, back pain causes',
        intro: 'Back pain affects millions of people and is one of the main causes of sick leave. In most cases it has muscular or postural origin and improves over time.',
        causes: [
          { name: 'Muscle contracture', description: 'Excessive tension in the back muscles due to poor posture, exertion or sedentary lifestyle.' },
          { name: 'Herniated disc', description: 'The intervertebral disc presses on a nerve, causing pain that can radiate to the arm or leg.' },
          { name: 'Scoliosis', description: 'Lateral curvature of the spine that generates muscular imbalance and chronic pain.' },
          { name: 'Osteoporosis', description: 'Loss of bone density that makes vertebrae more fragile and prone to fractures.' },
          { name: 'Stress and anxiety', description: 'Emotional tension frequently manifests as contractures in the dorsal area.' },
        ],
        redFlags: [
          'Pain appearing after trauma or fall',
          'Loss of strength or sensation in arms or legs',
          'Fever accompanying back pain',
          'Night pain that does not improve with any position',
          'Loss of bladder or bowel control',
        ],
        whenToAct: 'For common mechanical back pain, maintain moderate activity and apply local heat. If it does not improve within 2 weeks or any warning sign appears, consult your doctor.',
      },
      zh: {
        metaTitle: '背痛：原因及何时担忧',
        metaDescription: '关于背痛的信息指南：最常见的原因、风险因素、警告信号以及何时咨询医生。',
        keywords: '背痛, 背部疼痛, 背痛原因',
        intro: '背痛影响着数百万人，是病假的主要原因之一。大多数情况下具有肌肉或姿势性起源，随时间改善。',
        causes: [
          { name: '肌肉痉挛', description: '由于不良姿势、用力过度或久坐不动导致背部肌肉过度紧张。' },
          { name: '椎间盘突出', description: '椎间盘压迫神经，引起可能放射到手臂或腿部的疼痛。' },
          { name: '脊柱侧弯', description: '脊柱侧弯产生肌肉不平衡和慢性疼痛。' },
          { name: '骨质疏松症', description: '骨密度降低使椎骨更脆弱，容易骨折。' },
          { name: '压力和焦虑', description: '情绪紧张经常表现为背部区域的肌肉痉挛。' },
        ],
        redFlags: [
          '外伤或跌倒后出现的疼痛',
          '手臂或腿部力量或感觉丧失',
          '背痛伴发烧',
          '任何姿势都无法改善的夜间疼痛',
          '失去对膀胱或肠道的控制',
        ],
        whenToAct: '对于常见的机械性背痛，保持适度活动并局部热敷。如果2周内没有改善或出现任何警告信号，请咨询医生。',
      },
      ru: {
        metaTitle: 'Боль в спине: причины и когда беспокоиться',
        metaDescription: 'Информационное руководство по боли в спине: наиболее частые причины, факторы риска, тревожные признаки и когда обратиться к врачу.',
        keywords: 'боль в спине, дорсалгия, боль в верхней части спины, причины боли в спине',
        intro: 'Боль в спине затрагивает миллионы людей и является одной из главных причин больничных листов. В большинстве случаев имеет мышечное или постуральное происхождение и улучшается со временем.',
        causes: [
          { name: 'Мышечная контрактура', description: 'Чрезмерное напряжение мышц спины из-за плохой осанки, нагрузок или малоподвижного образа жизни.' },
          { name: 'Грыжа межпозвоночного диска', description: 'Межпозвоночный диск давит на нерв, вызывая боль, которая может отдавать в руку или ногу.' },
          { name: 'Сколиоз', description: 'Боковое искривление позвоночника, вызывающее мышечный дисбаланс и хроническую боль.' },
          { name: 'Остеопороз', description: 'Снижение плотности костей делает позвонки более хрупкими и склонными к переломам.' },
          { name: 'Стресс и тревога', description: 'Эмоциональное напряжение часто проявляется в виде контрактур в дорсальной области.' },
        ],
        redFlags: [
          'Боль после травмы или падения',
          'Потеря силы или чувствительности в руках или ногах',
          'Жар, сопровождающий боль в спине',
          'Ночная боль, которая не улучшается ни в какой позиции',
          'Потеря контроля над мочевым пузырём или кишечником',
        ],
        whenToAct: 'При обычной механической боли в спине поддерживайте умеренную активность и применяйте местное тепло. Если не улучшается в течение 2 недель или появляются тревожные признаки, обратитесь к врачу.',
      },
    },
  },
  {
    slug: 'dolor-lumbar',
    zone: 'lumbar',
    emoji: '🦴',
    related: ['dolor-de-espalda', 'dolor-muscular', 'dolor-de-rodilla'],
    content: {
      es: {
        metaTitle: 'Dolor lumbar: causas, síntomas y tratamiento general',
        metaDescription: 'Todo sobre el dolor lumbar o de la zona baja de la espalda: causas más frecuentes, ciática, señales de alarma y cuándo acudir al médico.',
        keywords: 'dolor lumbar, lumbalgia, dolor zona baja espalda, ciática, dolor lumbar causas',
        intro: 'El dolor lumbar o lumbalgia afecta al 80% de la población en algún momento de su vida. Es la primera causa de discapacidad laboral en el mundo y puede tener múltiples orígenes.',
        causes: [
          { name: 'Contractura lumbar', description: 'La causa más frecuente. Tensión muscular en la zona baja de la espalda por malas posturas o esfuerzos.' },
          { name: 'Hernia discal lumbar', description: 'Compresión de un nervio que puede provocar ciática: dolor que irradia por la pierna hasta el pie.' },
          { name: 'Artrosis lumbar', description: 'Desgaste de las articulaciones lumbares. Genera rigidez matutina y dolor que empeora con el movimiento prolongado.' },
          { name: 'Estenosis espinal', description: 'Estrechamiento del canal vertebral que comprime los nervios y causa dolor al caminar.' },
          { name: 'Sedentarismo', description: 'La falta de ejercicio debilita la musculatura lumbar y aumenta la sobrecarga sobre la columna.' },
        ],
        redFlags: [
          'Dolor que baja por la pierna con entumecimiento o debilidad (ciática severa)',
          'Pérdida de control de esfínteres',
          'Dolor nocturno intenso que no cede',
          'Fiebre con dolor lumbar',
          'Pérdida de peso inexplicable con el dolor',
        ],
        whenToAct: 'Mantén actividad moderada y evita el reposo absoluto. Aplica calor local. Si en 2 semanas no mejora o aparece ciática, consulta con tu médico o fisioterapeuta.',
      },
      en: {
        metaTitle: 'Lower back pain: causes, symptoms and general treatment',
        metaDescription: 'Everything about lower back pain: most common causes, sciatica, warning signs and when to see a doctor.',
        keywords: 'lower back pain, lumbago, lumbar pain, sciatica, lower back pain causes',
        intro: 'Lower back pain affects 80% of the population at some point in their lives. It is the leading cause of work disability worldwide and can have multiple origins.',
        causes: [
          { name: 'Lumbar contracture', description: 'The most frequent cause. Muscle tension in the lower back due to poor posture or exertion.' },
          { name: 'Lumbar herniated disc', description: 'Compression of a nerve that can cause sciatica: pain that radiates down the leg to the foot.' },
          { name: 'Lumbar osteoarthritis', description: 'Wear of the lumbar joints. Causes morning stiffness and pain that worsens with prolonged movement.' },
          { name: 'Spinal stenosis', description: 'Narrowing of the spinal canal that compresses nerves and causes pain when walking.' },
          { name: 'Sedentary lifestyle', description: 'Lack of exercise weakens the lumbar muscles and increases overload on the spine.' },
        ],
        redFlags: [
          'Pain radiating down the leg with numbness or weakness (severe sciatica)',
          'Loss of sphincter control',
          'Intense night pain that does not subside',
          'Fever with lower back pain',
          'Unexplained weight loss with pain',
        ],
        whenToAct: 'Maintain moderate activity and avoid complete rest. Apply local heat. If no improvement in 2 weeks or sciatica appears, consult your doctor or physiotherapist.',
      },
      zh: {
        metaTitle: '腰痛：原因、症状和一般治疗',
        metaDescription: '关于腰痛的一切：最常见的原因、坐骨神经痛、警告信号以及何时就医。',
        keywords: '腰痛, 腰背痛, 坐骨神经痛, 腰痛原因',
        intro: '腰痛在一生中某个时刻会影响80%的人口。它是全球工作残疾的主要原因，可能有多种起源。',
        causes: [
          { name: '腰部肌肉痉挛', description: '最常见的原因。由于不良姿势或用力过度导致腰部肌肉紧张。' },
          { name: '腰椎间盘突出', description: '神经受压可能导致坐骨神经痛：疼痛沿腿部向下放射到脚部。' },
          { name: '腰椎骨关节炎', description: '腰椎关节磨损。导致晨僵和长时间运动加重的疼痛。' },
          { name: '椎管狭窄', description: '椎管变窄压迫神经，导致行走时疼痛。' },
          { name: '久坐不动', description: '缺乏运动会削弱腰部肌肉并增加脊柱负担。' },
        ],
        redFlags: [
          '疼痛沿腿部放射伴麻木或无力（严重坐骨神经痛）',
          '括约肌控制丧失',
          '无法缓解的强烈夜间疼痛',
          '腰痛伴发烧',
          '疼痛伴不明原因体重减轻',
        ],
        whenToAct: '保持适度活动，避免完全卧床休息。局部热敷。如果2周内没有改善或出现坐骨神经痛，请咨询医生或物理治疗师。',
      },
      ru: {
        metaTitle: 'Боль в пояснице: причины, симптомы и общее лечение',
        metaDescription: 'Всё о боли в пояснице: наиболее частые причины, ишиас, тревожные признаки и когда обратиться к врачу.',
        keywords: 'боль в пояснице, люмбаго, поясничная боль, ишиас, причины поясничной боли',
        intro: 'Боль в пояснице затрагивает 80% населения в тот или иной момент жизни. Это ведущая причина трудовой инвалидности в мире, и она может иметь множество причин.',
        causes: [
          { name: 'Поясничная контрактура', description: 'Наиболее частая причина. Мышечное напряжение в пояснице из-за плохой осанки или нагрузок.' },
          { name: 'Поясничная грыжа диска', description: 'Сдавление нерва, которое может вызвать ишиас: боль, отдающая по ноге до стопы.' },
          { name: 'Поясничный остеоартроз', description: 'Износ поясничных суставов. Вызывает утреннюю скованность и боль, усиливающуюся при длительном движении.' },
          { name: 'Стеноз позвоночного канала', description: 'Сужение позвоночного канала, сдавливающее нервы и вызывающее боль при ходьбе.' },
          { name: 'Малоподвижный образ жизни', description: 'Недостаток физических упражнений ослабляет поясничные мышцы и увеличивает нагрузку на позвоночник.' },
        ],
        redFlags: [
          'Боль, отдающая по ноге с онемением или слабостью (тяжёлый ишиас)',
          'Потеря контроля над сфинктерами',
          'Интенсивная ночная боль, которая не стихает',
          'Жар с поясничной болью',
          'Необъяснимая потеря веса при боли',
        ],
        whenToAct: 'Поддерживайте умеренную активность и избегайте полного постельного режима. Применяйте местное тепло. Если через 2 недели улучшений нет или появляется ишиас, обратитесь к врачу или физиотерапевту.',
      },
    },
  },
  {
    slug: 'dolor-de-rodilla',
    zone: 'rodilla_izq',
    emoji: '🦿',
    related: ['dolor-muscular', 'dolor-lumbar', 'dolor-de-espalda'],
    content: {
      es: {
        metaTitle: 'Dolor de rodilla: causas frecuentes y cuándo actuar',
        metaDescription: 'Información sobre el dolor de rodilla: causas comunes como artrosis, menisco o ligamentos, señales de alarma y cuándo ir al médico.',
        keywords: 'dolor de rodilla, gonalgia, dolor rodilla causas, rodilla inflamada, artrosis rodilla',
        intro: 'El dolor de rodilla es uno de los problemas articulares más frecuentes. Puede aparecer en cualquier edad y tiene causas muy variadas, desde lesiones deportivas hasta desgaste articular.',
        causes: [
          { name: 'Síndrome femoropatelar', description: 'Alteración en el deslizamiento de la rótula. Causa dolor anterior que empeora al subir o bajar escaleras.' },
          { name: 'Lesión de menisco', description: 'El menisco actúa como amortiguador. Su lesión produce dolor, bloqueo e inflamación de la rodilla.' },
          { name: 'Ligamento cruzado', description: 'Lesión frecuente en deportistas. Produce inestabilidad y dolor intenso tras un movimiento brusco.' },
          { name: 'Artrosis', description: 'Desgaste del cartílago articular. Genera rigidez matutina, crujidos y dolor que aumenta con el uso.' },
          { name: 'Tendinitis rotuliana', description: 'Inflamación del tendón rotuliano. Dolor debajo de la rótula que empeora al correr o saltar.' },
        ],
        redFlags: [
          'Rodilla muy inflamada, caliente y roja tras un traumatismo',
          'Bloqueo completo de la rodilla',
          'Incapacidad para apoyar peso',
          'Deformidad visible de la rodilla',
          'Fiebre con inflamación de rodilla',
        ],
        whenToAct: 'Para dolor leve aplica hielo, reposa y evita sobrecarga. Si la inflamación es importante o el dolor persiste más de 1 semana, consulta con tu médico o traumatólogo.',
      },
      en: {
        metaTitle: 'Knee pain: common causes and when to act',
        metaDescription: 'Information about knee pain: common causes like osteoarthritis, meniscus or ligaments, warning signs and when to see a doctor.',
        keywords: 'knee pain, gonalgia, knee pain causes, swollen knee, knee osteoarthritis',
        intro: 'Knee pain is one of the most common joint problems. It can appear at any age and has very varied causes, from sports injuries to joint wear.',
        causes: [
          { name: 'Patellofemoral syndrome', description: 'Alteration in kneecap sliding. Causes anterior pain that worsens going up or down stairs.' },
          { name: 'Meniscus injury', description: 'The meniscus acts as a shock absorber. Its injury produces pain, blocking and swelling of the knee.' },
          { name: 'Cruciate ligament', description: 'Frequent injury in athletes. Produces instability and intense pain after a sudden movement.' },
          { name: 'Osteoarthritis', description: 'Wear of articular cartilage. Generates morning stiffness, cracking sounds and pain that increases with use.' },
          { name: 'Patellar tendinitis', description: 'Inflammation of the patellar tendon. Pain below the kneecap that worsens with running or jumping.' },
        ],
        redFlags: [
          'Very swollen, warm and red knee after trauma',
          'Complete knee locking',
          'Inability to bear weight',
          'Visible deformity of the knee',
          'Fever with knee inflammation',
        ],
        whenToAct: 'For mild pain apply ice, rest and avoid overload. If swelling is significant or pain persists more than 1 week, consult your doctor or orthopaedic specialist.',
      },
      zh: {
        metaTitle: '膝盖疼痛：常见原因及何时采取行动',
        metaDescription: '关于膝盖疼痛的信息：骨关节炎、半月板或韧带等常见原因、警告信号以及何时就医。',
        keywords: '膝盖疼痛, 膝关节痛, 膝盖痛原因, 膝盖肿胀, 膝关节炎',
        intro: '膝盖疼痛是最常见的关节问题之一。它可以出现在任何年龄，原因多种多样，从运动损伤到关节磨损。',
        causes: [
          { name: '髌骨股骨综合征', description: '髌骨滑动异常。导致前部疼痛，上下楼梯时加重。' },
          { name: '半月板损伤', description: '半月板起缓冲作用。损伤会产生疼痛、膝关节锁定和肿胀。' },
          { name: '十字韧带', description: '运动员常见损伤。突然动作后产生不稳定和剧烈疼痛。' },
          { name: '骨关节炎', description: '关节软骨磨损。产生晨僵、关节响声和随使用增加的疼痛。' },
          { name: '髌腱炎', description: '髌腱炎症。髌骨下方疼痛，跑步或跳跃时加重。' },
        ],
        redFlags: [
          '外伤后膝盖非常肿胀、发热和发红',
          '膝关节完全锁定',
          '无法承重',
          '膝盖可见变形',
          '膝盖炎症伴发烧',
        ],
        whenToAct: '轻微疼痛时冰敷、休息并避免过度负荷。如果肿胀明显或疼痛持续超过1周，请咨询医生或骨科专家。',
      },
      ru: {
        metaTitle: 'Боль в колене: частые причины и когда действовать',
        metaDescription: 'Информация о боли в колене: частые причины, такие как остеоартроз, мениск или связки, тревожные признаки и когда обратиться к врачу.',
        keywords: 'боль в колене, гоналгия, причины боли в колене, опухшее колено, артроз колена',
        intro: 'Боль в колене — одна из самых частых суставных проблем. Она может появиться в любом возрасте и имеет самые разные причины: от спортивных травм до износа сустава.',
        causes: [
          { name: 'Пателлофеморальный синдром', description: 'Нарушение скольжения надколенника. Вызывает переднюю боль, усиливающуюся при подъёме или спуске по лестнице.' },
          { name: 'Повреждение мениска', description: 'Мениск действует как амортизатор. Его повреждение вызывает боль, блокировку и отёк колена.' },
          { name: 'Крестообразная связка', description: 'Частая травма у спортсменов. Вызывает нестабильность и сильную боль после резкого движения.' },
          { name: 'Остеоартроз', description: 'Износ суставного хряща. Вызывает утреннюю скованность, хруст и боль, усиливающуюся при нагрузке.' },
          { name: 'Пателлярный тендинит', description: 'Воспаление сухожилия надколенника. Боль ниже надколенника, усиливающаяся при беге или прыжках.' },
        ],
        redFlags: [
          'Сильно опухшее, тёплое и красное колено после травмы',
          'Полная блокировка колена',
          'Невозможность нагружать ногу',
          'Видимая деформация колена',
          'Жар с воспалением колена',
        ],
        whenToAct: 'При лёгкой боли приложите лёд, отдыхайте и избегайте перегрузки. Если отёк значительный или боль не проходит более 1 недели, обратитесь к врачу или ортопеду.',
      },
    },
  },
  {
    slug: 'mareos-y-vertigo',
    zone: 'cabeza',
    emoji: '💫',
    related: ['dolor-de-cabeza', 'dolor-de-cuello', 'nauseas'],
    content: {
      es: {
        metaTitle: 'Mareos y vértigo: causas y cuándo consultar',
        metaDescription: 'Información sobre mareos y vértigo: diferencias, causas más frecuentes como el VPPB, señales de alarma y cuándo ir al médico.',
        keywords: 'mareos, vértigo, vértigo posicional, sensación de mareo, mareos causas',
        intro: 'El mareo y el vértigo son síntomas frecuentes que pueden tener múltiples causas. El vértigo es la sensación de que todo gira, mientras que el mareo es una sensación general de inestabilidad.',
        causes: [
          { name: 'VPPB (vértigo posicional)', description: 'La causa más frecuente de vértigo. Partículas en el oído interno que se desplazan con el movimiento.' },
          { name: 'Hipotensión ortostática', description: 'Bajada de tensión al levantarse bruscamente. Causa mareo pasajero que dura segundos.' },
          { name: 'Deshidratación', description: 'La falta de líquidos reduce el volumen sanguíneo y puede causar mareos, especialmente con calor.' },
          { name: 'Laberintitis', description: 'Inflamación del oído interno que causa vértigo intenso, náuseas y pérdida de equilibrio.' },
          { name: 'Anemia', description: 'Niveles bajos de hemoglobina que reducen el oxígeno al cerebro y causan mareos frecuentes.' },
        ],
        redFlags: [
          'Vértigo de inicio brusco con dolor de cabeza intenso',
          'Pérdida de audición súbita',
          'Visión doble o dificultad para hablar',
          'Debilidad en un lado del cuerpo',
          'Pérdida de conciencia',
        ],
        whenToAct: 'Si el mareo es breve y se relaciona con cambios de postura, observa y evita movimientos bruscos. Si el vértigo es intenso, persiste o aparece alguna señal de alarma, busca atención médica.',
      },
      en: {
        metaTitle: 'Dizziness and vertigo: causes and when to consult',
        metaDescription: 'Information about dizziness and vertigo: differences, most common causes like BPPV, warning signs and when to see a doctor.',
        keywords: 'dizziness, vertigo, positional vertigo, dizzy feeling, dizziness causes',
        intro: 'Dizziness and vertigo are frequent symptoms that can have multiple causes. Vertigo is the sensation that everything is spinning, while dizziness is a general feeling of instability.',
        causes: [
          { name: 'BPPV (positional vertigo)', description: 'The most frequent cause of vertigo. Particles in the inner ear that move with movement.' },
          { name: 'Orthostatic hypotension', description: 'Drop in blood pressure when standing up suddenly. Causes transient dizziness lasting seconds.' },
          { name: 'Dehydration', description: 'Lack of fluids reduces blood volume and can cause dizziness, especially in heat.' },
          { name: 'Labyrinthitis', description: 'Inflammation of the inner ear causing intense vertigo, nausea and loss of balance.' },
          { name: 'Anaemia', description: 'Low haemoglobin levels reduce oxygen to the brain and cause frequent dizziness.' },
        ],
        redFlags: [
          'Sudden onset vertigo with intense headache',
          'Sudden hearing loss',
          'Double vision or difficulty speaking',
          'Weakness on one side of the body',
          'Loss of consciousness',
        ],
        whenToAct: 'If dizziness is brief and related to position changes, observe and avoid sudden movements. If vertigo is intense, persists or any warning sign appears, seek medical attention.',
      },
      zh: {
        metaTitle: '头晕和眩晕：原因及何时就诊',
        metaDescription: '关于头晕和眩晕的信息：差异、BPPV等最常见原因、警告信号以及何时就医。',
        keywords: '头晕, 眩晕, 体位性眩晕, 头晕感, 头晕原因',
        intro: '头晕和眩晕是常见症状，可能有多种原因。眩晕是感觉一切都在旋转，而头晕是一种普遍的不稳定感。',
        causes: [
          { name: '良性阵发性位置性眩晕（BPPV）', description: '最常见的眩晕原因。内耳中的颗粒随运动移位。' },
          { name: '体位性低血压', description: '突然站立时血压下降。导致持续几秒钟的短暂头晕。' },
          { name: '脱水', description: '液体不足会降低血容量，尤其在炎热天气中可能导致头晕。' },
          { name: '迷路炎', description: '内耳炎症导致强烈眩晕、恶心和平衡失调。' },
          { name: '贫血', description: '低血红蛋白水平减少大脑供氧并导致频繁头晕。' },
        ],
        redFlags: [
          '突然发作的眩晕伴剧烈头痛',
          '突然听力丧失',
          '复视或言语困难',
          '身体一侧无力',
          '意识丧失',
        ],
        whenToAct: '如果头晕短暂且与体位变化有关，观察并避免突然动作。如果眩晕剧烈、持续或出现任何警告信号，请寻求医疗救助。',
      },
      ru: {
        metaTitle: 'Головокружение и вертиго: причины и когда обращаться',
        metaDescription: 'Информация о головокружении и вертиго: различия, наиболее частые причины, тревожные признаки и когда обратиться к врачу.',
        keywords: 'головокружение, вертиго, позиционное головокружение, ощущение головокружения, причины головокружения',
        intro: 'Головокружение и вертиго — частые симптомы, которые могут иметь множество причин. Вертиго — ощущение, что всё вращается, а головокружение — общее чувство неустойчивости.',
        causes: [
          { name: 'ДППГ (позиционное головокружение)', description: 'Наиболее частая причина вертиго. Частицы во внутреннем ухе, смещающиеся при движении.' },
          { name: 'Ортостатическая гипотензия', description: 'Падение давления при резком вставании. Вызывает кратковременное головокружение, длящееся секунды.' },
          { name: 'Обезвоживание', description: 'Недостаток жидкости снижает объём крови и может вызвать головокружение, особенно в жару.' },
          { name: 'Лабиринтит', description: 'Воспаление внутреннего уха, вызывающее интенсивное вертиго, тошноту и потерю равновесия.' },
          { name: 'Анемия', description: 'Низкий уровень гемоглобина снижает поступление кислорода в мозг и вызывает частое головокружение.' },
        ],
        redFlags: [
          'Внезапное вертиго с интенсивной головной болью',
          'Внезапная потеря слуха',
          'Двоение в глазах или затруднённая речь',
          'Слабость на одной стороне тела',
          'Потеря сознания',
        ],
        whenToAct: 'Если головокружение кратковременное и связано с изменением позы, наблюдайте и избегайте резких движений. Если вертиго интенсивное, не проходит или появляются тревожные признаки, обратитесь за медицинской помощью.',
      },
    },
  },
  {
    slug: 'dolor-de-cuello',
    zone: 'cuello',
    emoji: '🔵',
    related: ['dolor-de-cabeza', 'dolor-de-espalda', 'dolor-muscular'],
    content: {
      es: {
        metaTitle: 'Dolor de cuello: causas, cervicalgia y cuándo actuar',
        metaDescription: 'Guía sobre el dolor de cuello o cervicalgia: causas frecuentes, contracturas, artrosis cervical, señales de alarma y cuándo ir al médico.',
        keywords: 'dolor de cuello, cervicalgia, contractura cervical, tortícolis, dolor cuello causas',
        intro: 'El dolor de cuello o cervicalgia es uno de los síntomas más habituales en la población adulta, especialmente en personas que trabajan frente a pantallas.',
        causes: [
          { name: 'Contractura muscular cervical', description: 'Tensión de los músculos del cuello por malas posturas, estrés o frío. Es la causa más frecuente.' },
          { name: 'Tortícolis', description: 'Contractura aguda que bloquea el movimiento del cuello. Aparece frecuentemente al despertar.' },
          { name: 'Artrosis cervical', description: 'Desgaste de las vértebras cervicales. Produce rigidez, crujidos y dolor que puede irradiar al brazo.' },
          { name: 'Hernia cervical', description: 'Compresión de un nervio cervical que genera dolor, hormigueo o debilidad en el brazo.' },
          { name: 'Postura frente a pantallas', description: 'La posición adelantada del cuello frente al ordenador sobrecarga la musculatura cervical.' },
        ],
        redFlags: [
          'Dolor de cuello tras un traumatismo (accidente, caída)',
          'Hormigueo o pérdida de fuerza en brazos o manos',
          'Fiebre con rigidez de cuello intensa',
          'Dolor que irradia hacia el pecho o el brazo izquierdo',
          'Dificultad para tragar o respirar',
        ],
        whenToAct: 'Aplica calor, descansa y evita posturas forzadas. Si el dolor persiste más de 1 semana o aparece irradiación hacia el brazo, consulta con tu médico.',
      },
      en: {
        metaTitle: 'Neck pain: causes, cervicalgia and when to act',
        metaDescription: 'Guide to neck pain or cervicalgia: common causes, contractures, cervical osteoarthritis, warning signs and when to see a doctor.',
        keywords: 'neck pain, cervicalgia, neck contracture, torticollis, neck pain causes',
        intro: 'Neck pain or cervicalgia is one of the most common symptoms in the adult population, especially in people who work in front of screens.',
        causes: [
          { name: 'Cervical muscle contracture', description: 'Tension in neck muscles due to poor posture, stress or cold. The most frequent cause.' },
          { name: 'Torticollis', description: 'Acute contracture that blocks neck movement. Frequently appears upon waking.' },
          { name: 'Cervical osteoarthritis', description: 'Wear of cervical vertebrae. Produces stiffness, cracking and pain that can radiate to the arm.' },
          { name: 'Cervical hernia', description: 'Compression of a cervical nerve that causes pain, tingling or weakness in the arm.' },
          { name: 'Screen posture', description: 'The forward position of the neck in front of computers overloads the cervical muscles.' },
        ],
        redFlags: [
          'Neck pain after trauma (accident, fall)',
          'Tingling or loss of strength in arms or hands',
          'Fever with intense neck stiffness',
          'Pain radiating to chest or left arm',
          'Difficulty swallowing or breathing',
        ],
        whenToAct: 'Apply heat, rest and avoid forced postures. If pain persists more than 1 week or radiation to the arm appears, consult your doctor.',
      },
      zh: {
        metaTitle: '颈部疼痛：原因、颈椎病及何时采取行动',
        metaDescription: '颈部疼痛指南：常见原因、颈部肌肉痉挛、颈椎骨关节炎、警告信号以及何时就医。',
        keywords: '颈部疼痛, 颈椎病, 颈部肌肉痉挛, 斜颈, 颈痛原因',
        intro: '颈部疼痛是成年人最常见的症状之一，尤其是在屏幕前工作的人群中。',
        causes: [
          { name: '颈部肌肉痉挛', description: '由于不良姿势、压力或寒冷导致颈部肌肉紧张。最常见的原因。' },
          { name: '斜颈', description: '急性肌肉痉挛阻碍颈部运动。经常在醒来时出现。' },
          { name: '颈椎骨关节炎', description: '颈椎磨损。产生僵硬、关节响声和可能放射到手臂的疼痛。' },
          { name: '颈椎间盘突出', description: '颈神经受压导致手臂疼痛、麻木或无力。' },
          { name: '屏幕姿势', description: '在电脑前颈部向前倾的姿势会使颈部肌肉过度负荷。' },
        ],
        redFlags: [
          '外伤（事故、跌倒）后颈部疼痛',
          '手臂或手部麻木或无力',
          '发烧伴严重颈部僵硬',
          '疼痛放射到胸部或左臂',
          '吞咽或呼吸困难',
        ],
        whenToAct: '热敷、休息并避免强迫姿势。如果疼痛持续超过1周或出现放射到手臂的疼痛，请咨询医生。',
      },
      ru: {
        metaTitle: 'Боль в шее: причины, цервикалгия и когда действовать',
        metaDescription: 'Руководство по боли в шее: частые причины, контрактуры, шейный остеоартроз, тревожные признаки и когда обратиться к врачу.',
        keywords: 'боль в шее, цервикалгия, шейная контрактура, кривошея, причины боли в шее',
        intro: 'Боль в шее или цервикалгия — один из самых распространённых симптомов среди взрослого населения, особенно у людей, работающих перед экранами.',
        causes: [
          { name: 'Шейная мышечная контрактура', description: 'Напряжение мышц шеи из-за плохой осанки, стресса или холода. Наиболее частая причина.' },
          { name: 'Кривошея', description: 'Острая контрактура, блокирующая движение шеи. Часто появляется при пробуждении.' },
          { name: 'Шейный остеоартроз', description: 'Износ шейных позвонков. Вызывает скованность, хруст и боль, которая может отдавать в руку.' },
          { name: 'Шейная грыжа', description: 'Сдавление шейного нерва, вызывающее боль, покалывание или слабость в руке.' },
          { name: 'Поза перед экраном', description: 'Положение шеи вперёд перед компьютером перегружает шейные мышцы.' },
        ],
        redFlags: [
          'Боль в шее после травмы (авария, падение)',
          'Покалывание или потеря силы в руках или кистях',
          'Жар с интенсивной ригидностью шеи',
          'Боль, отдающая в грудь или левую руку',
          'Затруднения при глотании или дыхании',
        ],
        whenToAct: 'Приложите тепло, отдыхайте и избегайте вынужденных поз. Если боль не проходит более 1 недели или появляется иррадиация в руку, обратитесь к врачу.',
      },
    },
  },
  {
    slug: 'dolor-muscular',
    zone: 'pecho',
    emoji: '💪',
    related: ['dolor-de-espalda', 'dolor-lumbar', 'dolor-de-cuello'],
    content: {
      es: {
        metaTitle: 'Dolor muscular: causas, mialgia y cuándo preocuparse',
        metaDescription: 'Información sobre el dolor muscular o mialgia: causas frecuentes, agujetas, fibromialgia y cuándo consultar al médico.',
        keywords: 'dolor muscular, mialgia, agujetas, fibromialgia, dolor en los músculos',
        intro: 'El dolor muscular o mialgia es extremadamente frecuente y en la mayoría de los casos tiene causas benignas como el ejercicio físico, el estrés o infecciones virales.',
        causes: [
          { name: 'Ejercicio físico (agujetas)', description: 'Microdesgarros musculares tras el ejercicio. El dolor aparece 24-48 horas después y se resuelve solo.' },
          { name: 'Contractura muscular', description: 'Contracción involuntaria y sostenida de un músculo por sobreesfuerzo, estrés o malas posturas.' },
          { name: 'Infecciones virales', description: 'La gripe y otras infecciones pueden causar dolores musculares generalizados (mialgias).' },
          { name: 'Deshidratación', description: 'La falta de líquidos y electrolitos puede provocar calambres y dolor muscular.' },
          { name: 'Fibromialgia', description: 'Síndrome de dolor muscular crónico y generalizado, acompañado de fatiga y alteraciones del sueño.' },
        ],
        redFlags: [
          'Debilidad muscular progresiva sin dolor previo',
          'Dolor muscular intenso tras tomar ciertos medicamentos (estatinas)',
          'Orina oscura acompañando el dolor muscular (posible rabdomiólisis)',
          'Fiebre alta con dolor muscular intenso',
          'Dolor muscular localizado que aumenta progresivamente',
        ],
        whenToAct: 'Para las agujetas y contracturas leves, descansa, aplica calor y mantén hidratación. Si el dolor es intenso, generalizado o va a peor, consulta con tu médico.',
      },
      en: {
        metaTitle: 'Muscle pain: causes, myalgia and when to worry',
        metaDescription: 'Information about muscle pain or myalgia: common causes, delayed onset muscle soreness, fibromyalgia and when to consult a doctor.',
        keywords: 'muscle pain, myalgia, DOMS, fibromyalgia, muscle soreness',
        intro: 'Muscle pain or myalgia is extremely common and in most cases has benign causes such as physical exercise, stress or viral infections.',
        causes: [
          { name: 'Physical exercise (DOMS)', description: 'Muscle micro-tears after exercise. Pain appears 24-48 hours later and resolves on its own.' },
          { name: 'Muscle contracture', description: 'Involuntary and sustained contraction of a muscle due to overexertion, stress or poor posture.' },
          { name: 'Viral infections', description: 'Flu and other infections can cause generalised muscle pain (myalgias).' },
          { name: 'Dehydration', description: 'Lack of fluids and electrolytes can cause cramps and muscle pain.' },
          { name: 'Fibromyalgia', description: 'Syndrome of chronic and generalised muscle pain, accompanied by fatigue and sleep disturbances.' },
        ],
        redFlags: [
          'Progressive muscle weakness without prior pain',
          'Intense muscle pain after taking certain medications (statins)',
          'Dark urine accompanying muscle pain (possible rhabdomyolysis)',
          'High fever with intense muscle pain',
          'Localised muscle pain that progressively worsens',
        ],
        whenToAct: 'For mild DOMS and contractures, rest, apply heat and stay hydrated. If pain is intense, generalised or worsening, consult your doctor.',
      },
      zh: {
        metaTitle: '肌肉疼痛：原因、肌痛及何时担忧',
        metaDescription: '关于肌肉疼痛的信息：常见原因、延迟性肌肉酸痛、纤维肌痛及何时就医。',
        keywords: '肌肉疼痛, 肌痛, 延迟性肌肉酸痛, 纤维肌痛, 肌肉酸痛',
        intro: '肌肉疼痛非常常见，大多数情况下有良性原因，如体育锻炼、压力或病毒感染。',
        causes: [
          { name: '体育锻炼（延迟性肌肉酸痛）', description: '运动后肌肉微撕裂。疼痛在24-48小时后出现，自行消退。' },
          { name: '肌肉痉挛', description: '由于过度劳累、压力或不良姿势导致肌肉不自主持续收缩。' },
          { name: '病毒感染', description: '流感和其他感染可能导致全身肌肉疼痛（肌痛）。' },
          { name: '脱水', description: '液体和电解质不足可能导致抽筋和肌肉疼痛。' },
          { name: '纤维肌痛', description: '慢性全身性肌肉疼痛综合征，伴有疲劳和睡眠障碍。' },
        ],
        redFlags: [
          '无先前疼痛的进行性肌肉无力',
          '服用某些药物（他汀类）后的强烈肌肉疼痛',
          '肌肉疼痛伴深色尿液（可能是横纹肌溶解）',
          '高烧伴强烈肌肉疼痛',
          '局部肌肉疼痛逐渐加重',
        ],
        whenToAct: '对于轻微延迟性肌肉酸痛和肌肉痉挛，休息、热敷并保持水分补充。如果疼痛剧烈、全身性或加重，请咨询医生。',
      },
      ru: {
        metaTitle: 'Мышечная боль: причины, миалгия и когда беспокоиться',
        metaDescription: 'Информация о мышечной боли или миалгии: частые причины, крепатура, фибромиалгия и когда обратиться к врачу.',
        keywords: 'мышечная боль, миалгия, крепатура, фибромиалгия, боль в мышцах',
        intro: 'Мышечная боль или миалгия чрезвычайно распространена и в большинстве случаев имеет доброкачественные причины: физические упражнения, стресс или вирусные инфекции.',
        causes: [
          { name: 'Физические упражнения (крепатура)', description: 'Микроразрывы мышц после нагрузки. Боль появляется через 24-48 часов и проходит сама.' },
          { name: 'Мышечная контрактура', description: 'Непроизвольное и устойчивое сокращение мышцы из-за перегрузки, стресса или плохой осанки.' },
          { name: 'Вирусные инфекции', description: 'Грипп и другие инфекции могут вызывать генерализованную мышечную боль (миалгии).' },
          { name: 'Обезвоживание', description: 'Недостаток жидкости и электролитов может вызывать судороги и мышечную боль.' },
          { name: 'Фибромиалгия', description: 'Синдром хронической и генерализованной мышечной боли, сопровождаемый усталостью и нарушениями сна.' },
        ],
        redFlags: [
          'Прогрессирующая мышечная слабость без предшествующей боли',
          'Интенсивная мышечная боль после приёма некоторых лекарств (статинов)',
          'Тёмная моча при мышечной боли (возможный рабдомиолиз)',
          'Высокая температура с интенсивной мышечной болью',
          'Локализованная мышечная боль, прогрессивно усиливающаяся',
        ],
        whenToAct: 'При лёгкой крепатуре и контрактурах отдыхайте, применяйте тепло и поддерживайте водный баланс. Если боль интенсивная, генерализованная или усиливается, обратитесь к врачу.',
      },
    },
  },
  {
    slug: 'dolor-abdominal',
    zone: 'abdomen',
    emoji: '🫃',
    related: ['nauseas', 'dolor-de-espalda', 'dolor-lumbar'],
    content: {
      es: {
        metaTitle: 'Dolor abdominal: causas y cuándo ir a urgencias',
        metaDescription: 'Guía sobre el dolor abdominal: tipos, causas más frecuentes por zona, señales de urgencia y cuándo consultar al médico.',
        keywords: 'dolor abdominal, dolor de estómago, dolor barriga, dolor abdomen causas, apendicitis',
        intro: 'El dolor abdominal es uno de los síntomas más frecuentes en la consulta médica. Puede tener causas muy diversas, desde problemas digestivos benignos hasta situaciones que requieren atención urgente.',
        causes: [
          { name: 'Gases y distensión', description: 'La acumulación de gas en el intestino provoca dolor tipo cólico que mejora al expulsarlo.' },
          { name: 'Gastroenteritis', description: 'Infección digestiva que causa dolor abdominal, diarrea, náuseas y vómitos.' },
          { name: 'Síndrome de intestino irritable', description: 'Trastorno funcional que genera dolor, distensión y cambios en el ritmo intestinal.' },
          { name: 'Apendicitis', description: 'Dolor que empieza difuso y se localiza en el lado derecho inferior. Requiere atención urgente.' },
          { name: 'Cólico biliar', description: 'Dolor intenso en el lado derecho superior tras comidas grasas. Relacionado con la vesícula.' },
        ],
        redFlags: [
          'Dolor muy intenso de inicio brusco',
          'Abdomen rígido como tabla al tacto',
          'Vómitos con sangre o heces negras',
          'Fiebre alta con dolor abdominal',
          'Ictericia (piel o ojos amarillos)',
        ],
        whenToAct: 'Si el dolor es leve y mejora con el movimiento intestinal, observa. Si es intenso, localizado en cuadrante inferior derecho o se acompaña de fiebre, busca atención médica urgente.',
      },
      en: {
        metaTitle: 'Abdominal pain: causes and when to go to emergency',
        metaDescription: 'Guide to abdominal pain: types, most common causes by zone, emergency signs and when to consult a doctor.',
        keywords: 'abdominal pain, stomach pain, belly pain, abdominal pain causes, appendicitis',
        intro: 'Abdominal pain is one of the most frequent symptoms in medical consultations. It can have very diverse causes, from benign digestive problems to situations requiring urgent attention.',
        causes: [
          { name: 'Gas and bloating', description: 'Accumulation of gas in the intestine causes colicky pain that improves when expelled.' },
          { name: 'Gastroenteritis', description: 'Digestive infection causing abdominal pain, diarrhoea, nausea and vomiting.' },
          { name: 'Irritable bowel syndrome', description: 'Functional disorder causing pain, bloating and changes in bowel rhythm.' },
          { name: 'Appendicitis', description: 'Pain that starts diffuse and localises in the lower right side. Requires urgent attention.' },
          { name: 'Biliary colic', description: 'Intense pain in the upper right side after fatty meals. Related to the gallbladder.' },
        ],
        redFlags: [
          'Very intense sudden onset pain',
          'Rigid abdomen like a board to touch',
          'Vomiting blood or black stools',
          'High fever with abdominal pain',
          'Jaundice (yellow skin or eyes)',
        ],
        whenToAct: 'If pain is mild and improves with bowel movement, observe. If intense, localised in lower right quadrant or accompanied by fever, seek urgent medical attention.',
      },
      zh: {
        metaTitle: '腹痛：原因及何时去急诊',
        metaDescription: '腹痛指南：类型、各区域最常见原因、紧急信号以及何时就医。',
        keywords: '腹痛, 胃痛, 肚子痛, 腹痛原因, 阑尾炎',
        intro: '腹痛是医疗咨询中最常见的症状之一。它可能有非常多样的原因，从良性消化问题到需要紧急关注的情况。',
        causes: [
          { name: '气体和腹胀', description: '肠道中气体积聚导致绞痛，排出后改善。' },
          { name: '肠胃炎', description: '消化道感染导致腹痛、腹泻、恶心和呕吐。' },
          { name: '肠易激综合征', description: '功能性障碍导致疼痛、腹胀和排便规律改变。' },
          { name: '阑尾炎', description: '疼痛从弥漫开始，定位于右下侧。需要紧急关注。' },
          { name: '胆绞痛', description: '进食油腻食物后右上侧剧烈疼痛。与胆囊有关。' },
        ],
        redFlags: [
          '突然发作的非常剧烈的疼痛',
          '腹部触摸时僵硬如板',
          '呕吐血液或黑色粪便',
          '腹痛伴高烧',
          '黄疸（皮肤或眼睛发黄）',
        ],
        whenToAct: '如果疼痛轻微，排便后改善，观察即可。如果剧烈，定位于右下腹，或伴有发烧，立即寻求紧急医疗救助。',
      },
      ru: {
        metaTitle: 'Боль в животе: причины и когда обращаться в скорую',
        metaDescription: 'Руководство по боли в животе: типы, наиболее частые причины по зонам, признаки срочности и когда обратиться к врачу.',
        keywords: 'боль в животе, боль в желудке, боль в брюшной полости, причины боли в животе, аппендицит',
        intro: 'Боль в животе — один из самых частых симптомов на медицинских консультациях. Может иметь самые разные причины: от доброкачественных пищеварительных проблем до ситуаций, требующих неотложной помощи.',
        causes: [
          { name: 'Газы и вздутие', description: 'Скопление газов в кишечнике вызывает схваткообразную боль, которая проходит при их отхождении.' },
          { name: 'Гастроэнтерит', description: 'Пищеварительная инфекция, вызывающая боль в животе, диарею, тошноту и рвоту.' },
          { name: 'Синдром раздражённого кишечника', description: 'Функциональное расстройство, вызывающее боль, вздутие и изменения ритма кишечника.' },
          { name: 'Аппендицит', description: 'Боль, начинающаяся диффузно и локализующаяся в нижней правой части. Требует неотложной помощи.' },
          { name: 'Желчная колика', description: 'Интенсивная боль в верхней правой части после жирной пищи. Связана с желчным пузырём.' },
        ],
        redFlags: [
          'Очень интенсивная внезапная боль',
          'Живот твёрдый как доска при пальпации',
          'Рвота кровью или чёрный стул',
          'Высокая температура с болью в животе',
          'Желтуха (жёлтая кожа или глаза)',
        ],
        whenToAct: 'Если боль слабая и улучшается при дефекации, наблюдайте. Если интенсивная, локализована в нижнем правом квадранте или сопровождается жаром, срочно обратитесь за медицинской помощью.',
      },
    },
  },
  {
    slug: 'dolor-de-garganta',
    zone: 'cuello',
    emoji: '🗣️',
    related: ['dolor-de-cabeza', 'dolor-de-cuello', 'mareos-y-vertigo'],
    content: {
      es: {
        metaTitle: 'Dolor de garganta: causas, anginas y cuándo actuar',
        metaDescription: 'Información sobre el dolor de garganta: diferencia entre viral y bacteriana, anginas, señales de alarma y cuándo ir al médico.',
        keywords: 'dolor de garganta, faringitis, amigdalitis, anginas, garganta inflamada',
        intro: 'El dolor de garganta es uno de los motivos de consulta médica más frecuentes, especialmente en otoño e invierno. En la mayoría de los casos tiene origen viral y se resuelve solo en pocos días.',
        causes: [
          { name: 'Faringitis viral', description: 'La causa más frecuente. Causada por rinovirus, adenovirus u otros. Se acompaña de catarro y mejora sola.' },
          { name: 'Faringitis bacteriana (Streptococo)', description: 'Infección por Streptococo que requiere antibiótico. Causa dolor intenso, fiebre y placas blanquecinas.' },
          { name: 'Amigdalitis', description: 'Inflamación de las amígdalas. Puede ser viral o bacteriana. Produce dificultad para tragar.' },
          { name: 'Reflujo gastroesofágico', description: 'El ácido estomacal irrita la garganta y puede causar carraspeo y molestia crónica.' },
          { name: 'Sequedad ambiental', description: 'El aire seco, especialmente con calefacción, irrita la mucosa faríngea.' },
        ],
        redFlags: [
          'Dificultad grave para respirar o tragar',
          'Voz muy apagada o dificultad para abrir la boca',
          'Fiebre muy alta (más de 39°C) que no baja',
          'Dolor de garganta que dura más de 10 días',
          'Manchas o placas en la garganta con fiebre alta',
        ],
        whenToAct: 'Para el dolor de garganta leve, reposa, hidratate y usa analgésicos suaves. Si tienes fiebre alta, placas o el dolor persiste más de 5-7 días, consulta con tu médico para descartar infección bacteriana.',
      },
      en: {
        metaTitle: 'Sore throat: causes, tonsillitis and when to act',
        metaDescription: 'Information about sore throat: difference between viral and bacterial, tonsillitis, warning signs and when to see a doctor.',
        keywords: 'sore throat, pharyngitis, tonsillitis, strep throat, inflamed throat',
        intro: 'Sore throat is one of the most frequent reasons for medical consultation, especially in autumn and winter. In most cases it has viral origin and resolves on its own in a few days.',
        causes: [
          { name: 'Viral pharyngitis', description: 'The most frequent cause. Caused by rhinovirus, adenovirus or others. Accompanied by cold symptoms and improves on its own.' },
          { name: 'Bacterial pharyngitis (Streptococcus)', description: 'Streptococcal infection requiring antibiotics. Causes intense pain, fever and white patches.' },
          { name: 'Tonsillitis', description: 'Inflammation of the tonsils. Can be viral or bacterial. Causes difficulty swallowing.' },
          { name: 'Gastroesophageal reflux', description: 'Stomach acid irritates the throat and can cause chronic hoarseness and discomfort.' },
          { name: 'Environmental dryness', description: 'Dry air, especially with heating, irritates the pharyngeal mucosa.' },
        ],
        redFlags: [
          'Severe difficulty breathing or swallowing',
          'Very muffled voice or difficulty opening mouth',
          'Very high fever (above 39°C) that does not subside',
          'Sore throat lasting more than 10 days',
          'Spots or patches in throat with high fever',
        ],
        whenToAct: 'For mild sore throat, rest, hydrate and use mild analgesics. If you have high fever, patches or pain persists more than 5-7 days, consult your doctor to rule out bacterial infection.',
      },
      zh: {
        metaTitle: '喉咙痛：原因、扁桃体炎及何时采取行动',
        metaDescription: '关于喉咙痛的信息：病毒性和细菌性的区别、扁桃体炎、警告信号以及何时就医。',
        keywords: '喉咙痛, 咽炎, 扁桃体炎, 链球菌咽炎, 喉咙发炎',
        intro: '喉咙痛是医疗咨询最常见的原因之一，尤其在秋冬季节。大多数情况下为病毒性，几天内自行消退。',
        causes: [
          { name: '病毒性咽炎', description: '最常见的原因。由鼻病毒、腺病毒或其他病毒引起。伴有感冒症状，自行改善。' },
          { name: '细菌性咽炎（链球菌）', description: '需要抗生素的链球菌感染。导致剧烈疼痛、发烧和白色斑块。' },
          { name: '扁桃体炎', description: '扁桃体发炎。可能是病毒性或细菌性。导致吞咽困难。' },
          { name: '胃食管反流', description: '胃酸刺激喉咙，可能导致慢性嘶哑和不适。' },
          { name: '环境干燥', description: '干燥空气，尤其是暖气，会刺激咽部黏膜。' },
        ],
        redFlags: [
          '严重的呼吸或吞咽困难',
          '声音非常沙哑或张口困难',
          '持续不退的高烧（39°C以上）',
          '喉咙痛持续超过10天',
          '高烧伴喉咙斑点或斑块',
        ],
        whenToAct: '轻微喉咙痛时，休息、补水并使用温和止痛药。如果有高烧、斑块或疼痛持续超过5-7天，请咨询医生排除细菌感染。',
      },
      ru: {
        metaTitle: 'Боль в горле: причины, тонзиллит и когда действовать',
        metaDescription: 'Информация о боли в горле: разница между вирусной и бактериальной, тонзиллит, тревожные признаки и когда обратиться к врачу.',
        keywords: 'боль в горле, фарингит, тонзиллит, стрептококковый фарингит, воспалённое горло',
        intro: 'Боль в горле — одна из наиболее частых причин обращения к врачу, особенно осенью и зимой. В большинстве случаев имеет вирусное происхождение и проходит сама за несколько дней.',
        causes: [
          { name: 'Вирусный фарингит', description: 'Наиболее частая причина. Вызван риновирусом, аденовирусом или другими. Сопровождается простудой и проходит сам.' },
          { name: 'Бактериальный фарингит (стрептококк)', description: 'Стрептококковая инфекция, требующая антибиотиков. Вызывает сильную боль, жар и белые налёты.' },
          { name: 'Тонзиллит', description: 'Воспаление миндалин. Может быть вирусным или бактериальным. Вызывает трудности с глотанием.' },
          { name: 'Гастроэзофагеальный рефлюкс', description: 'Желудочная кислота раздражает горло и может вызывать хрипоту и хронический дискомфорт.' },
          { name: 'Сухость воздуха', description: 'Сухой воздух, особенно при отоплении, раздражает слизистую оболочку глотки.' },
        ],
        redFlags: [
          'Серьёзные затруднения дыхания или глотания',
          'Очень сиплый голос или трудности с открыванием рта',
          'Очень высокая температура (выше 39°C), которая не спадает',
          'Боль в горле, длящаяся более 10 дней',
          'Пятна или налёты в горле при высокой температуре',
        ],
        whenToAct: 'При лёгкой боли в горле отдыхайте, пейте больше жидкости и принимайте мягкие анальгетики. Если есть высокая температура, налёты или боль не проходит более 5-7 дней, обратитесь к врачу.',
      },
    },
  },
  {
    slug: 'dolor-de-hombro',
    zone: 'hombro_izq',
    emoji: '💪',
    related: ['dolor-de-cuello', 'dolor-muscular', 'dolor-de-espalda'],
    content: {
      es: {
        metaTitle: 'Dolor de hombro: causas, manguito y cuándo actuar',
        metaDescription: 'Información sobre el dolor de hombro: causas frecuentes como el manguito rotador, hombro congelado y cuándo consultar al médico.',
        keywords: 'dolor de hombro, manguito rotador, hombro congelado, tendinitis hombro, dolor hombro causas',
        intro: 'El dolor de hombro es el tercer problema musculoesquelético más frecuente tras el dolor de espalda y el de cuello. Puede limitar significativamente la movilidad del brazo.',
        causes: [
          { name: 'Tendinitis del manguito rotador', description: 'Inflamación de los tendones que rodean el hombro. Dolor al elevar el brazo por encima de la cabeza.' },
          { name: 'Hombro congelado (capsulitis)', description: 'Rigidez progresiva y dolor constante del hombro. La movilidad se reduce gradualmente.' },
          { name: 'Bursitis', description: 'Inflamación de la bolsa sinovial del hombro. Causa dolor al mover el brazo y al dormir.' },
          { name: 'Artrosis de hombro', description: 'Desgaste articular que genera dolor crónico y limitación de movimiento.' },
          { name: 'Contractura del trapecio', description: 'Tensión del músculo trapecio que puede irradiar dolor hacia el hombro y el cuello.' },
        ],
        redFlags: [
          'Dolor de hombro izquierdo con presión en el pecho y sudoración fría',
          'Imposibilidad total de mover el hombro tras un traumatismo',
          'Deformidad visible del hombro',
          'Pérdida de fuerza repentina en el brazo',
          'Fiebre con dolor e inflamación de hombro',
        ],
        whenToAct: 'Aplica frío en lesiones agudas y calor en dolor crónico. Evita movimientos que agraven el dolor. Si no mejora en 2 semanas o hay pérdida de movilidad importante, consulta con tu médico.',
      },
      en: {
        metaTitle: 'Shoulder pain: causes, rotator cuff and when to act',
        metaDescription: 'Information about shoulder pain: common causes like rotator cuff, frozen shoulder and when to consult a doctor.',
        keywords: 'shoulder pain, rotator cuff, frozen shoulder, shoulder tendinitis, shoulder pain causes',
        intro: 'Shoulder pain is the third most frequent musculoskeletal problem after back and neck pain. It can significantly limit arm mobility.',
        causes: [
          { name: 'Rotator cuff tendinitis', description: 'Inflammation of the tendons surrounding the shoulder. Pain when raising the arm above the head.' },
          { name: 'Frozen shoulder (capsulitis)', description: 'Progressive stiffness and constant shoulder pain. Mobility gradually decreases.' },
          { name: 'Bursitis', description: 'Inflammation of the shoulder synovial bursa. Causes pain when moving the arm and when sleeping.' },
          { name: 'Shoulder osteoarthritis', description: 'Joint wear that generates chronic pain and movement limitation.' },
          { name: 'Trapezius contracture', description: 'Trapezius muscle tension that can radiate pain towards the shoulder and neck.' },
        ],
        redFlags: [
          'Left shoulder pain with chest pressure and cold sweating',
          'Total inability to move shoulder after trauma',
          'Visible shoulder deformity',
          'Sudden loss of strength in arm',
          'Fever with shoulder pain and inflammation',
        ],
        whenToAct: 'Apply cold for acute injuries and heat for chronic pain. Avoid movements that aggravate pain. If no improvement in 2 weeks or significant mobility loss, consult your doctor.',
      },
      zh: {
        metaTitle: '肩部疼痛：原因、肩袖及何时采取行动',
        metaDescription: '关于肩部疼痛的信息：肩袖、冻结肩等常见原因以及何时就医。',
        keywords: '肩部疼痛, 肩袖, 冻结肩, 肩部肌腱炎, 肩痛原因',
        intro: '肩部疼痛是继背痛和颈痛之后第三常见的肌肉骨骼问题。它可能显著限制手臂的活动能力。',
        causes: [
          { name: '肩袖肌腱炎', description: '肩部周围肌腱发炎。将手臂抬过头顶时疼痛。' },
          { name: '冻结肩（关节囊炎）', description: '肩部进行性僵硬和持续疼痛。活动能力逐渐下降。' },
          { name: '滑囊炎', description: '肩部滑囊发炎。移动手臂和睡觉时疼痛。' },
          { name: '肩关节骨关节炎', description: '关节磨损导致慢性疼痛和活动受限。' },
          { name: '斜方肌痉挛', description: '斜方肌紧张可能向肩部和颈部放射疼痛。' },
        ],
        redFlags: [
          '左肩疼痛伴胸部压迫感和冷汗',
          '外伤后完全无法移动肩部',
          '肩部可见变形',
          '手臂突然失去力量',
          '发烧伴肩部疼痛和炎症',
        ],
        whenToAct: '急性损伤冷敷，慢性疼痛热敷。避免加重疼痛的动作。如果2周内没有改善或活动能力明显丧失，请咨询医生。',
      },
      ru: {
        metaTitle: 'Боль в плече: причины, манжета ротатора и когда действовать',
        metaDescription: 'Информация о боли в плече: частые причины — манжета ротатора, замороженное плечо — и когда обратиться к врачу.',
        keywords: 'боль в плече, манжета ротатора, замороженное плечо, тендинит плеча, причины боли в плече',
        intro: 'Боль в плече — третья по частоте скелетно-мышечная проблема после боли в спине и шее. Она может значительно ограничить подвижность руки.',
        causes: [
          { name: 'Тендинит манжеты ротатора', description: 'Воспаление сухожилий, окружающих плечо. Боль при поднятии руки над головой.' },
          { name: 'Замороженное плечо (капсулит)', description: 'Прогрессирующая скованность и постоянная боль в плече. Подвижность постепенно уменьшается.' },
          { name: 'Бурсит', description: 'Воспаление суставной сумки плеча. Вызывает боль при движении рукой и во время сна.' },
          { name: 'Артроз плеча', description: 'Износ сустава, вызывающий хроническую боль и ограничение движений.' },
          { name: 'Контрактура трапеции', description: 'Напряжение трапециевидной мышцы, которое может отдавать боль в плечо и шею.' },
        ],
        redFlags: [
          'Боль в левом плече с давлением в груди и холодным потом',
          'Полная невозможность двигать плечом после травмы',
          'Видимая деформация плеча',
          'Внезапная потеря силы в руке',
          'Жар с болью и воспалением плеча',
        ],
        whenToAct: 'При острых травмах прикладывайте холод, при хронической боли — тепло. Избегайте движений, усиливающих боль. Если нет улучшения через 2 недели или значительная потеря подвижности, обратитесь к врачу.',
      },
    },
  },
  {
    slug: 'dolor-en-el-pecho',
    zone: 'pecho',
    emoji: '❤️',
    related: ['mareos-y-vertigo', 'dolor-de-hombro', 'dolor-de-espalda'],
    content: {
      es: {
        metaTitle: 'Dolor en el pecho: causas y cuándo llamar al 112',
        metaDescription: 'Guía sobre el dolor torácico: causas más frecuentes, diferencia entre dolor cardíaco y muscular, señales de alarma y cuándo actuar.',
        keywords: 'dolor en el pecho, dolor torácico, dolor pecho causas, infarto síntomas, angina de pecho',
        intro: 'El dolor en el pecho es uno de los síntomas que más preocupación genera. Aunque la mayoría de las veces tiene origen muscular o digestivo, siempre debe tomarse en serio.',
        causes: [
          { name: 'Costocondritis', description: 'Inflamación del cartílago entre las costillas y el esternón. Dolor que empeora al presionar el pecho.' },
          { name: 'Tensión muscular intercostal', description: 'Contractura de los músculos intercostales por esfuerzo o tos intensa. Dolor localizado al respirar.' },
          { name: 'Reflujo gastroesofágico', description: 'El ácido estomacal genera ardor y presión en el pecho que puede confundirse con dolor cardíaco.' },
          { name: 'Ansiedad y pánico', description: 'La ansiedad puede causar opresión en el pecho, taquicardia y dificultad para respirar.' },
          { name: 'Pleuritis', description: 'Inflamación de la membrana que recubre los pulmones. Dolor agudo que empeora al respirar hondo.' },
        ],
        redFlags: [
          'Dolor intenso que irradia al brazo izquierdo, mandíbula o espalda',
          'Sudoración fría repentina con el dolor',
          'Dificultad para respirar en reposo',
          'Dolor que dura más de 15-20 minutos',
          'Labios o uñas azulados',
        ],
        whenToAct: 'Si el dolor es leve, localizado y empeora al presionar, probablemente es muscular. Si es opresivo, irradia o se acompaña de los síntomas anteriores, llama al 112 inmediatamente.',
      },
      en: {
        metaTitle: 'Chest pain: causes and when to call emergency services',
        metaDescription: 'Guide to chest pain: most common causes, difference between cardiac and muscular pain, warning signs and when to act.',
        keywords: 'chest pain, thoracic pain, chest pain causes, heart attack symptoms, angina',
        intro: 'Chest pain is one of the symptoms that causes most concern. Although most of the time it has muscular or digestive origin, it should always be taken seriously.',
        causes: [
          { name: 'Costochondritis', description: 'Inflammation of the cartilage between the ribs and sternum. Pain that worsens when pressing the chest.' },
          { name: 'Intercostal muscle tension', description: 'Contracture of intercostal muscles from exertion or intense coughing. Localised pain when breathing.' },
          { name: 'Gastroesophageal reflux', description: 'Stomach acid creates burning and chest pressure that can be confused with cardiac pain.' },
          { name: 'Anxiety and panic', description: 'Anxiety can cause chest tightness, rapid heartbeat and difficulty breathing.' },
          { name: 'Pleuritis', description: 'Inflammation of the membrane surrounding the lungs. Sharp pain that worsens with deep breathing.' },
        ],
        redFlags: [
          'Intense pain radiating to left arm, jaw or back',
          'Sudden cold sweating with pain',
          'Difficulty breathing at rest',
          'Pain lasting more than 15-20 minutes',
          'Blue lips or nails',
        ],
        whenToAct: 'If pain is mild, localised and worsens when pressing, it is probably muscular. If it is oppressive, radiates or is accompanied by the above symptoms, call emergency services immediately.',
      },
      zh: {
        metaTitle: '胸部疼痛：原因及何时拨打急救电话',
        metaDescription: '关于胸痛的指南：最常见原因、心脏性和肌肉性疼痛的区别、警告信号以及何时采取行动。',
        keywords: '胸部疼痛, 胸痛, 胸痛原因, 心脏病发作症状, 心绞痛',
        intro: '胸部疼痛是引起最多担忧的症状之一。虽然大多数时候起源于肌肉或消化系统，但应该始终认真对待。',
        causes: [
          { name: '肋软骨炎', description: '肋骨和胸骨之间软骨发炎。按压胸部时疼痛加重。' },
          { name: '肋间肌紧张', description: '因用力或剧烈咳嗽导致肋间肌肉痉挛。呼吸时局部疼痛。' },
          { name: '胃食管反流', description: '胃酸产生烧灼感和胸部压力，可能与心脏疼痛混淆。' },
          { name: '焦虑和恐慌', description: '焦虑可能导致胸闷、心跳加速和呼吸困难。' },
          { name: '胸膜炎', description: '肺部覆盖膜发炎。深呼吸时加重的剧烈疼痛。' },
        ],
        redFlags: [
          '向左臂、下颌或背部放射的剧烈疼痛',
          '疼痛时突然冷汗',
          '静息时呼吸困难',
          '疼痛持续超过15-20分钟',
          '嘴唇或指甲发蓝',
        ],
        whenToAct: '如果疼痛轻微、局限且按压时加重，可能是肌肉性的。如果是压迫性、放射性或伴有上述症状，立即拨打急救电话。',
      },
      ru: {
        metaTitle: 'Боль в груди: причины и когда звонить в скорую',
        metaDescription: 'Руководство по боли в груди: наиболее частые причины, разница между сердечной и мышечной болью, тревожные признаки и когда действовать.',
        keywords: 'боль в груди, торакалгия, причины боли в груди, симптомы инфаркта, стенокардия',
        intro: 'Боль в груди — один из симптомов, вызывающих наибольшее беспокойство. Хотя в большинстве случаев имеет мышечное или пищеварительное происхождение, к ней всегда следует относиться серьёзно.',
        causes: [
          { name: 'Костохондрит', description: 'Воспаление хряща между рёбрами и грудиной. Боль усиливается при надавливании на грудь.' },
          { name: 'Напряжение межрёберных мышц', description: 'Контрактура межрёберных мышц от нагрузки или интенсивного кашля. Локализованная боль при дыхании.' },
          { name: 'Гастроэзофагеальный рефлюкс', description: 'Желудочная кислота создаёт жжение и давление в груди, которое можно спутать с сердечной болью.' },
          { name: 'Тревога и паника', description: 'Тревога может вызывать сжатие в груди, учащённое сердцебиение и затруднённое дыхание.' },
          { name: 'Плеврит', description: 'Воспаление оболочки лёгких. Острая боль, усиливающаяся при глубоком вдохе.' },
        ],
        redFlags: [
          'Интенсивная боль, отдающая в левую руку, челюсть или спину',
          'Внезапный холодный пот с болью',
          'Затруднённое дыхание в покое',
          'Боль, длящаяся более 15-20 минут',
          'Синюшные губы или ногти',
        ],
        whenToAct: 'Если боль слабая, локализованная и усиливается при надавливании, вероятно, она мышечная. Если давящая, отдаёт или сопровождается вышеуказанными симптомами, немедленно вызывайте скорую.',
      },
    },
  },
  {
    slug: 'nauseas',
    zone: 'abdomen',
    emoji: '🤢',
    related: ['dolor-abdominal', 'mareos-y-vertigo', 'dolor-de-cabeza'],
    content: {
      es: {
        metaTitle: 'Náuseas: causas frecuentes y cuándo consultar al médico',
        metaDescription: 'Información sobre las náuseas: causas más comunes, diferencia con mareo, señales de alarma y cuándo ir al médico.',
        keywords: 'náuseas, ganas de vomitar, náuseas causas, náuseas y vómitos, mareo con náuseas',
        intro: 'Las náuseas son una sensación de malestar en el estómago con deseo de vomitar. Son un síntoma muy frecuente que puede acompañar a múltiples condiciones.',
        causes: [
          { name: 'Gastroenteritis', description: 'Infección digestiva que causa náuseas, vómitos y diarrea. Suele resolverse en 24-72 horas.' },
          { name: 'Intoxicación alimentaria', description: 'Ingestión de alimentos en mal estado. Náuseas y vómitos de inicio rápido tras la comida.' },
          { name: 'Cinetosis (mareo por movimiento)', description: 'Conflicto entre los sentidos visual y vestibular durante el transporte.' },
          { name: 'Embarazo', description: 'Las náuseas matutinas son muy frecuentes en el primer trimestre del embarazo.' },
          { name: 'Medicamentos', description: 'Muchos fármacos producen náuseas como efecto secundario, especialmente antibióticos y analgésicos.' },
        ],
        redFlags: [
          'Vómitos con sangre o material oscuro',
          'Náuseas con dolor de cabeza intenso y rigidez de cuello',
          'Signos de deshidratación grave (ojos hundidos, piel seca, sin orina)',
          'Náuseas tras un traumatismo craneal',
          'Vómitos que impiden mantener cualquier líquido durante más de 24 horas',
        ],
        whenToAct: 'Para náuseas leves, descansa, come en pequeñas cantidades y mantén hidratación. Si los vómitos son persistentes o aparece alguna señal de alarma, busca atención médica.',
      },
      en: {
        metaTitle: 'Nausea: common causes and when to consult a doctor',
        metaDescription: 'Information about nausea: most common causes, difference from dizziness, warning signs and when to see a doctor.',
        keywords: 'nausea, feeling sick, nausea causes, nausea and vomiting, dizziness with nausea',
        intro: 'Nausea is a feeling of discomfort in the stomach with the urge to vomit. It is a very common symptom that can accompany multiple conditions.',
        causes: [
          { name: 'Gastroenteritis', description: 'Digestive infection causing nausea, vomiting and diarrhoea. Usually resolves in 24-72 hours.' },
          { name: 'Food poisoning', description: 'Ingestion of spoiled food. Nausea and vomiting starting quickly after eating.' },
          { name: 'Motion sickness', description: 'Conflict between visual and vestibular senses during transport.' },
          { name: 'Pregnancy', description: 'Morning sickness is very common in the first trimester of pregnancy.' },
          { name: 'Medications', description: 'Many drugs produce nausea as a side effect, especially antibiotics and analgesics.' },
        ],
        redFlags: [
          'Vomiting blood or dark material',
          'Nausea with intense headache and neck stiffness',
          'Signs of severe dehydration (sunken eyes, dry skin, no urine)',
          'Nausea after head trauma',
          'Vomiting preventing any fluids for more than 24 hours',
        ],
        whenToAct: 'For mild nausea, rest, eat in small amounts and stay hydrated. If vomiting is persistent or any warning sign appears, seek medical attention.',
      },
      zh: {
        metaTitle: '恶心：常见原因及何时就医',
        metaDescription: '关于恶心的信息：最常见原因、与头晕的区别、警告信号以及何时就医。',
        keywords: '恶心, 想吐, 恶心原因, 恶心和呕吐, 头晕伴恶心',
        intro: '恶心是胃部不适伴有呕吐冲动的感觉。这是一种非常常见的症状，可能伴随多种疾病。',
        causes: [
          { name: '肠胃炎', description: '消化道感染导致恶心、呕吐和腹泻。通常在24-72小时内消退。' },
          { name: '食物中毒', description: '食用变质食物。进食后迅速出现恶心和呕吐。' },
          { name: '晕动症', description: '乘坐交通工具时视觉和前庭感觉之间的冲突。' },
          { name: '妊娠', description: '早孕反应在妊娠早期非常常见。' },
          { name: '药物', description: '许多药物会产生恶心作为副作用，尤其是抗生素和止痛药。' },
        ],
        redFlags: [
          '呕吐血液或深色物质',
          '恶心伴剧烈头痛和颈部僵硬',
          '严重脱水迹象（眼窝深陷、皮肤干燥、无尿）',
          '头部创伤后恶心',
          '超过24小时无法保持任何液体的呕吐',
        ],
        whenToAct: '轻度恶心时，休息、少量进食并保持水分补充。如果呕吐持续或出现任何警告信号，请寻求医疗救助。',
      },
      ru: {
        metaTitle: 'Тошнота: частые причины и когда обратиться к врачу',
        metaDescription: 'Информация о тошноте: наиболее частые причины, отличие от головокружения, тревожные признаки и когда обратиться к врачу.',
        keywords: 'тошнота, позывы к рвоте, причины тошноты, тошнота и рвота, головокружение с тошнотой',
        intro: 'Тошнота — ощущение дискомфорта в желудке с позывами к рвоте. Это очень частый симптом, который может сопровождать множество состояний.',
        causes: [
          { name: 'Гастроэнтерит', description: 'Пищеварительная инфекция, вызывающая тошноту, рвоту и диарею. Обычно проходит за 24-72 часа.' },
          { name: 'Пищевое отравление', description: 'Употребление испорченной пищи. Тошнота и рвота начинаются быстро после еды.' },
          { name: 'Укачивание', description: 'Конфликт между зрительным и вестибулярным восприятием во время транспортировки.' },
          { name: 'Беременность', description: 'Утренняя тошнота очень распространена в первом триместре беременности.' },
          { name: 'Лекарства', description: 'Многие препараты вызывают тошноту как побочный эффект, особенно антибиотики и анальгетики.' },
        ],
        redFlags: [
          'Рвота кровью или тёмным содержимым',
          'Тошнота с интенсивной головной болью и ригидностью шеи',
          'Признаки тяжёлого обезвоживания (запавшие глаза, сухая кожа, отсутствие мочи)',
          'Тошнота после черепно-мозговой травмы',
          'Рвота, не позволяющая удержать никакую жидкость более 24 часов',
        ],
        whenToAct: 'При лёгкой тошноте отдыхайте, ешьте небольшими порциями и поддерживайте водный баланс. Если рвота не прекращается или появляются тревожные признаки, обратитесь за медицинской помощью.',
      },
    },
  },
];

export const SYMPTOM_SLUGS = SYMPTOMS.map(s => s.slug);

export function getSymptom(slug: string): Symptom | undefined {
  return SYMPTOMS.find(s => s.slug === slug);
}

export function getRelatedSymptoms(slug: string): Symptom[] {
  const symptom = getSymptom(slug);
  if (!symptom) return [];
  return symptom.related
    .map(s => getSymptom(s))
    .filter((s): s is Symptom => s !== undefined);
}